# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Thu Apr  4 21:03:06 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabTransmit = QtWidgets.QWidget()
        self.tabTransmit.setObjectName("tabTransmit")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabTransmit)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalWidget = QtWidgets.QWidget(self.tabTransmit)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_13.addWidget(self.label_3, 0, 0, 1, 1)
        self.btnSetCode = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetCode.sizePolicy().hasHeightForWidth())
        self.btnSetCode.setSizePolicy(sizePolicy)
        self.btnSetCode.setObjectName("btnSetCode")
        self.gridLayout_13.addWidget(self.btnSetCode, 1, 2, 1, 1)
        self.btnGenerateCode = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.btnGenerateCode.sizePolicy().hasHeightForWidth())
        self.btnGenerateCode.setSizePolicy(sizePolicy)
        self.btnGenerateCode.setObjectName("btnGenerateCode")
        self.gridLayout_13.addWidget(self.btnGenerateCode, 1, 1, 1, 1)
        self.txtSecretCode = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.txtSecretCode.sizePolicy().hasHeightForWidth())
        self.txtSecretCode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSecretCode.setFont(font)
        self.txtSecretCode.setText("")
        self.txtSecretCode.setReadOnly(False)
        self.txtSecretCode.setObjectName("txtSecretCode")
        self.gridLayout_13.addWidget(self.txtSecretCode, 1, 0, 1, 1)
        self.btnCopyCode = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCopyCode.sizePolicy().hasHeightForWidth())
        self.btnCopyCode.setSizePolicy(sizePolicy)
        self.btnCopyCode.setObjectName("btnCopyCode")
        self.gridLayout_13.addWidget(self.btnCopyCode, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.widget_2 = QtWidgets.QWidget(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_9.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_12.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_12.addWidget(self.label_9, 9, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem, 11, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 2, 0, 1, 1)
        self.btnSendFile = QtWidgets.QPushButton(self.frame_3)
        self.btnSendFile.setObjectName("btnSendFile")
        self.gridLayout_12.addWidget(self.btnSendFile, 11, 0, 1, 1)
        self.progressSendFile = QtWidgets.QProgressBar(self.frame_3)
        self.progressSendFile.setProperty("value", 0)
        self.progressSendFile.setObjectName("progressSendFile")
        self.gridLayout_12.addWidget(self.progressSendFile, 10, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem1, 12, 0, 1, 1)
        self.btnBrowseFile = QtWidgets.QPushButton(self.frame_3)
        self.btnBrowseFile.setObjectName("btnBrowseFile")
        self.gridLayout_12.addWidget(self.btnBrowseFile, 6, 0, 1, 1)
        self.txtFileName = QtWidgets.QLineEdit(self.frame_3)
        self.txtFileName.setObjectName("txtFileName")
        self.gridLayout_12.addWidget(self.txtFileName, 4, 0, 2, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem3, 6, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem4, 8, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 0, 0, 1, 1)
        self.btnSendMsg = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSendMsg.sizePolicy().hasHeightForWidth())
        self.btnSendMsg.setSizePolicy(sizePolicy)
        self.btnSendMsg.setObjectName("btnSendMsg")
        self.gridLayout_10.addWidget(self.btnSendMsg, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem5, 2, 1, 1, 1)
        self.txtMessage = QtWidgets.QPlainTextEdit(self.frame_2)
        self.txtMessage.setObjectName("txtMessage")
        self.gridLayout_10.addWidget(self.txtMessage, 1, 0, 1, 2)
        self.horizontalLayout.addWidget(self.frame_2)
        self.gridLayout_9.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtProgressSend = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtProgressSend.sizePolicy().hasHeightForWidth())
        self.txtProgressSend.setSizePolicy(sizePolicy)
        self.txtProgressSend.setObjectName("txtProgressSend")
        self.horizontalLayout_2.addWidget(self.txtProgressSend)
        self.verticalLayout.addWidget(self.widget_3)
        self.gridLayout_8.addWidget(self.verticalWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabTransmit, "")
        self.tabReceive = QtWidgets.QWidget()
        self.tabReceive.setObjectName("tabReceive")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tabReceive)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.widget_4 = QtWidgets.QWidget(self.tabReceive)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.txtFolderName = QtWidgets.QLineEdit(self.frame_5)
        self.txtFolderName.setObjectName("txtFolderName")
        self.gridLayout_16.addWidget(self.txtFolderName, 4, 0, 2, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem6, 12, 0, 1, 1)
        self.lblRecvFileName = QtWidgets.QLabel(self.frame_5)
        self.lblRecvFileName.setText("")
        self.lblRecvFileName.setObjectName("lblRecvFileName")
        self.gridLayout_16.addWidget(self.lblRecvFileName, 9, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem7, 7, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_16.addWidget(self.label_18, 11, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setDigitCount(15)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_16.addWidget(self.lcdNumber, 11, 1, 1, 1)
        self.btnBrowseFolder = QtWidgets.QPushButton(self.frame_5)
        self.btnBrowseFolder.setObjectName("btnBrowseFolder")
        self.gridLayout_16.addWidget(self.btnBrowseFolder, 6, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem8, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_16.addWidget(self.label_12, 13, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_16.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_16.addWidget(self.label_17, 9, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_16.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_16.addWidget(self.label_16, 8, 0, 1, 1)
        self.progressRecvFile = QtWidgets.QProgressBar(self.frame_5)
        self.progressRecvFile.setProperty("value", 0)
        self.progressRecvFile.setObjectName("progressRecvFile")
        self.gridLayout_16.addWidget(self.progressRecvFile, 14, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem9, 6, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_15 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_17.addWidget(self.label_15, 0, 0, 1, 1)
        self.txtMessageRecv = QtWidgets.QPlainTextEdit(self.frame_6)
        self.txtMessageRecv.setReadOnly(True)
        self.txtMessageRecv.setObjectName("txtMessageRecv")
        self.gridLayout_17.addWidget(self.txtMessageRecv, 1, 0, 1, 3)
        self.chkAppend = QtWidgets.QCheckBox(self.frame_6)
        self.chkAppend.setChecked(True)
        self.chkAppend.setObjectName("chkAppend")
        self.gridLayout_17.addWidget(self.chkAppend, 2, 2, 1, 1)
        self.btnClearRecvMsg = QtWidgets.QPushButton(self.frame_6)
        self.btnClearRecvMsg.setObjectName("btnClearRecvMsg")
        self.gridLayout_17.addWidget(self.btnClearRecvMsg, 2, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem10, 2, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.frame_4 = QtWidgets.QFrame(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.txtSecretCodeRecv = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.txtSecretCodeRecv.sizePolicy().hasHeightForWidth())
        self.txtSecretCodeRecv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSecretCodeRecv.setFont(font)
        self.txtSecretCodeRecv.setText("")
        self.txtSecretCodeRecv.setReadOnly(False)
        self.txtSecretCodeRecv.setObjectName("txtSecretCodeRecv")
        self.gridLayout_14.addWidget(self.txtSecretCodeRecv, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_14.addWidget(self.label_10, 0, 0, 1, 1)
        self.btnPasteCode = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPasteCode.sizePolicy().hasHeightForWidth())
        self.btnPasteCode.setSizePolicy(sizePolicy)
        self.btnPasteCode.setObjectName("btnPasteCode")
        self.gridLayout_14.addWidget(self.btnPasteCode, 1, 2, 1, 1)
        self.btnSetCodeRecv = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetCodeRecv.sizePolicy().hasHeightForWidth())
        self.btnSetCodeRecv.setSizePolicy(sizePolicy)
        self.btnSetCodeRecv.setObjectName("btnSetCodeRecv")
        self.gridLayout_14.addWidget(self.btnSetCodeRecv, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.gridLayout_15.addWidget(self.widget_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabReceive, "")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabSettings)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget = QtWidgets.QWidget(self.tabSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setContentsMargins(100, 10, 50, -1)
        self.formLayout.setHorizontalSpacing(50)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtRelay = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtRelay.sizePolicy().hasHeightForWidth())
        self.txtRelay.setSizePolicy(sizePolicy)
        self.txtRelay.setText("")
        self.txtRelay.setObjectName("txtRelay")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtRelay)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtAppID = QtWidgets.QLineEdit(self.widget)
        self.txtAppID.setObjectName("txtAppID")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtAppID)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.txtTransit = QtWidgets.QLineEdit(self.widget)
        self.txtTransit.setObjectName("txtTransit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtTransit)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.gridLayout_4.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget, 0, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.tabSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setObjectName("widget1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setContentsMargins(100, -1, 100, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnSaveSetup = QtWidgets.QPushButton(self.widget1)
        self.btnSaveSetup.setObjectName("btnSaveSetup")
        self.gridLayout_6.addWidget(self.btnSaveSetup, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget1, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSettings, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.txtLog = QtWidgets.QPlainTextEdit(self.tab)
        self.txtLog.setReadOnly(True)
        self.txtLog.setObjectName("txtLog")
        self.gridLayout_11.addWidget(self.txtLog, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionWormhole = QtWidgets.QAction(MainWindow)
        self.actionWormhole.setObjectName("actionWormhole")
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionWormhole)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Codice segreto", None, -1))
        self.btnSetCode.setText(QtWidgets.QApplication.translate("MainWindow", "Imposta\n"
"Manualmente", None, -1))
        self.btnGenerateCode.setText(QtWidgets.QApplication.translate("MainWindow", "Genera", None, -1))
        self.btnCopyCode.setText(QtWidgets.QApplication.translate("MainWindow", "Copia", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Invia un file", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Trasferimento", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Selezione file", None, -1))
        self.btnSendFile.setText(QtWidgets.QApplication.translate("MainWindow", "Invia", None, -1))
        self.btnBrowseFile.setText(QtWidgets.QApplication.translate("MainWindow", "sfoglia", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Invia un messaggio", None, -1))
        self.btnSendMsg.setText(QtWidgets.QApplication.translate("MainWindow", "Invia", None, -1))
        self.txtProgressSend.setText(QtWidgets.QApplication.translate("MainWindow", "Messages+Files: 0 | ACKs: 0", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTransmit), QtWidgets.QApplication.translate("MainWindow", "Invia", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "Dimensioni (bytes):", None, -1))
        self.btnBrowseFolder.setText(QtWidgets.QApplication.translate("MainWindow", "sfoglia", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Trasferimento", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Ricezione file", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Nome:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Directory destinazione:", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Dettagli File:", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Ricezione testo", None, -1))
        self.chkAppend.setText(QtWidgets.QApplication.translate("MainWindow", "Appendi", None, -1))
        self.btnClearRecvMsg.setText(QtWidgets.QApplication.translate("MainWindow", "Svuota", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Codice segreto", None, -1))
        self.btnPasteCode.setText(QtWidgets.QApplication.translate("MainWindow", "Incolla", None, -1))
        self.btnSetCodeRecv.setText(QtWidgets.QApplication.translate("MainWindow", "Conferma\n"
"Trasferimento", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReceive), QtWidgets.QApplication.translate("MainWindow", "Ricevi", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Rendez-Vous relay:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "App ID:", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Transit relay:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Lingua:", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Default sistema", None, -1))
        self.btnSaveSetup.setText(QtWidgets.QApplication.translate("MainWindow", "Salva", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), QtWidgets.QApplication.translate("MainWindow", "Setup", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Logging", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionWormhole.setText(QtWidgets.QApplication.translate("MainWindow", "Connetti wormhole", None, -1))
        self.actionOpenFile.setText(QtWidgets.QApplication.translate("MainWindow", "Seleziona file...", None, -1))
        self.actionQuit.setText(QtWidgets.QApplication.translate("MainWindow", "Esci", None, -1))

import resources_rc
